mod to work with linuxserver wireguard docker

diff --git a/wg-clients-guardian b/wg-clients-guardian
--- a/wg-clients-guardian
+++ b/wg-clients-guardian
@@ -6,10 +6,10 @@
 # Credits: This script is inspired by https://github.com/pivpn/pivpn/blob/master/scripts/wireguard/clientSTAT.sh
 
 # check if wireguard exists
-if ! command -v wg &> /dev/null; then
-	printf "Sorry, but wireguard is required. Install it and try again.\n"
-	exit 1;
-fi
+#if ! command -v wg &> /dev/null; then
+#	printf "Sorry, but wireguard is required. Install it and try again.\n"
+#	exit 1;
+#fi
 
 # check if the user passed in the config file and that the file exists
 if [ ! "$1" ]; then
@@ -29,7 +29,7 @@ readonly NOW=$(date +%s)
 # after X minutes the clients will be considered disconnected
 readonly TIMEOUT=$(awk -F'=' '/^timeout=/ { print $2}' $1)
 
-readonly WIREGUARD_CLIENTS=$(wg show wg0 dump | tail -n +2) # remove first line from list
+readonly WIREGUARD_CLIENTS=$(docker exec wireguard wg show wg0 dump | tail -n +2) # remove first line from list
 if [ "" == "$WIREGUARD_CLIENTS" ]; then
 	printf "No wireguard clients.\n"
 	exit 1
@@ -48,7 +48,7 @@ while IFS= read -r LINE; do
 	public_key=$(awk '{ print $1 }' <<< "$LINE")
 	remote_ip=$(awk '{ print $3 }' <<< "$LINE" | awk -F':' '{print $1}')
 	last_seen=$(awk '{ print $5 }' <<< "$LINE")
-	client_name=$(grep -R "$public_key" /etc/wireguard/keys/ | awk -F"/etc/wireguard/keys/|_pub:" '{print $2}' | sed -e 's./..g')
+	client_name=${public_key:0:3}
 	client_file="$CLIENTS_DIRECTORY/$client_name.txt"
 
 	# create the client file if it does not exist.
@@ -93,7 +93,7 @@ while IFS= read -r LINE; do
 		printf "The client %s is %s\n" $client_name $send_notification
 		message="$client_name is $send_notification from ip address $remote_ip"
     if [ "telegram" == "$NOTIFICATION_CHANNEL" ] || [ "both" == "$NOTIFICATION_CHANNEL" ]; then
-      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -F chat_id=$TELEGRAM_CHAT_ID -F text="🐉 Wireguard: \`$message\`" -F parse_mode="MarkdownV2" > /dev/null 2>&1
+      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -F chat_id=$TELEGRAM_CHAT_ID -F text="ðŸ‰ Wireguard: \`$message\`" -F parse_mode="MarkdownV2" > /dev/null 2>&1
     fi
     if [ "gotify" == "$NOTIFICATION_CHANNEL" ] || [ "both" == "$NOTIFICATION_CHANNEL" ]; then
       curl -X POST "${GOTIFY_HOST}/message" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ${GOTIFY_APP_TOKEN}" -d '{"message": "'"$message"'", "priority": 5, "title": "'"$GOTIFY_TITLE"'"}' > /dev/null 2>&1
